---
- hosts: 172.31.10.225
  become: yes

  tasks:
    - include_tasks: myfile.yml

    - name: Create a folder
      file:
        path: /home/rupa/myfolder
        state: directory

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Copy a file into the node
      copy:
        src: mytestfile
        dest: /home/rupa/myfolder
        force: yes
      notify: startwebserver

    - name: Download a file from the internet
      get_url:
        url: https://updates.jenkins.io/download/war/2.509/jenkins.war
        dest: /home/rupa/myfolder/jenkins.war
        force: true
      notify: startwebserver

    - name: Copy index file into node
      template:
        src: myindex.j2
        dest: /var/www/html/index.html
        force: yes
      notify: startwebserver

  handlers:
    - name: startwebserver
      service:
        name: apache2
        state: restarted
