---
- hosts: 172.31.10.225
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a folder
    file: 
      path: /home/rupa/myfolder
      state: directory
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
  - name: i want to copy a file into node side
    copy:
      src: mytestfile
      dest: /home/rupa/myfolder
  
  - name: i want to download internet file
    get_url:
      url: https://updates.jenkins.io/download/war/2.509/jenkins.war
      dest: /home/rupa/myfolder
      force_basic_auth: yes