---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubuntu (apt-get install apache2 )
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"


  - name: i want to start webserver on ubuntu (service apache2 start)
    service:
      name: apache2
      state: started    
    when: ansible_os_family == "Debian"  