---
# tasks file for mytomcatrole
- include_tasks: installjava.yml
- include_tasks: downloadtomcat.yml
- include_tasks: addusergroup.yml
- include_tasks: permission.yml
- include_tasks: tomcatservice.yml
- include_tasks: starttomcat.yml