---
- name: Change owner on tomcat folder
  command: "chown -R tomcat: /opt/tomcat"

- name: Give execute permission on all .sh files in bin directory
  shell: "chmod +x /opt/tomcat/bin/*.sh"
  args:
    executable: /bin/bash
